### ISSUE TITLE
Test alternative base images

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/webviz-docker#5]
Use https://github.com/tiangolo/meinheld-gunicorn-flask-docker instead of https://github.com/tiangolo/uwsgi-nginx-flask-docker?

> If you need to use Flask (instead of something based on ASGI) and you need to have the best performance possible, you can use the alternative image: tiangolo/meinheld-gunicorn-flask.
> 
> tiangolo/meinheld-gunicorn-flask will give you about 400% (4x) the performance of this image (tiangolo/uwsgi-nginx-flask).
> 
> It is very similar to tiangolo/uwsgi-nginx-flask, so you can still use many of the ideas described here.

[(source)](https://github.com/tiangolo/uwsgi-nginx-flask-docker#if-you-need-flask)

**Comment by HansKallekleiv** [comment]
Sounds promising.
There is one issue in that repo with regards to Plotly Dash apps that might be relevant.
